import '../models/country.dart';

final List<ModelCountry> countries = [
  ModelCountry(name: 'Afghanistan', code: 'AF'),
  ModelCountry(name: 'Åland Islands', code: 'AX'),
  ModelCountry(name: 'Albania', code: 'AL'),
  ModelCountry(name: 'Algeria', code: 'DZ'),
  ModelCountry(name: 'American Samoa', code: 'AS'),
  ModelCountry(name: 'AndorrA', code: 'AD'),
  ModelCountry(name: 'Angola', code: 'AO'),
  ModelCountry(name: 'Anguilla', code: 'AI'),
  ModelCountry(name: 'Antarctica', code: 'AQ'),
  ModelCountry(name: 'Antigua and Barbuda', code: 'AG'),
  ModelCountry(name: 'Argentina', code: 'AR'),
  ModelCountry(name: 'Armenia', code: 'AM'),
  ModelCountry(name: 'Aruba', code: 'AW'),
  ModelCountry(name: 'Australia', code: 'AU'),
  ModelCountry(name: 'Austria', code: 'AT'),
  ModelCountry(name: 'Azerbaijan', code: 'AZ'),
  ModelCountry(name: 'Bahamas', code: 'BS'),
  ModelCountry(name: 'Bahrain', code: 'BH'),
  ModelCountry(name: 'Bangladesh', code: 'BD'),
  ModelCountry(name: 'Barbados', code: 'BB'),
  ModelCountry(name: 'Belarus', code: 'BY'),
  ModelCountry(name: 'Belgium', code: 'BE'),
  ModelCountry(name: 'Belize', code: 'BZ'),
  ModelCountry(name: 'Benin', code: 'BJ'),
  ModelCountry(name: 'Bermuda', code: 'BM'),
  ModelCountry(name: 'Bhutan', code: 'BT'),
  ModelCountry(name: 'Bolivia', code: 'BO'),
  ModelCountry(name: 'Bosnia and Herzegovina', code: 'BA'),
  ModelCountry(name: 'Botswana', code: 'BW'),
  ModelCountry(name: 'Bouvet Island', code: 'BV'),
  ModelCountry(name: 'Brazil', code: 'BR'),
  ModelCountry(name: 'British Indian Ocean Territory', code: 'IO'),
  ModelCountry(name: 'Brunei Darussalam', code: 'BN'),
  ModelCountry(name: 'Bulgaria', code: 'BG'),
  ModelCountry(name: 'Burkina Faso', code: 'BF'),
  ModelCountry(name: 'Burundi', code: 'BI'),
  ModelCountry(name: 'Cambodia', code: 'KH'),
  ModelCountry(name: 'Cameroon', code: 'CM'),
  ModelCountry(name: 'Canada', code: 'CA'),
  ModelCountry(name: 'Cape Verde', code: 'CV'),
  ModelCountry(name: 'Cayman Islands', code: 'KY'),
  ModelCountry(name: 'Central African Republic', code: 'CF'),
  ModelCountry(name: 'Chad', code: 'TD'),
  ModelCountry(name: 'Chile', code: 'CL'),
  ModelCountry(name: 'China', code: 'CN'),
  ModelCountry(name: 'Christmas Island', code: 'CX'),
  ModelCountry(name: 'Cocos (Keeling) Islands', code: 'CC'),
  ModelCountry(name: 'Colombia', code: 'CO'),
  ModelCountry(name: 'Comoros', code: 'KM'),
  ModelCountry(name: 'Congo', code: 'CG'),
  ModelCountry(name: 'Congo, The Democratic Republic of the', code: 'CD'),
  ModelCountry(name: 'Cook Islands', code: 'CK'),
  ModelCountry(name: 'Costa Rica', code: 'CR'),
  ModelCountry(name: 'Cote D\'Ivoire', code: 'CI'),
  ModelCountry(name: 'Croatia', code: 'HR'),
  ModelCountry(name: 'Cuba', code: 'CU'),
  ModelCountry(name: 'Cyprus', code: 'CY'),
  ModelCountry(name: 'Czech Republic', code: 'CZ'),
  ModelCountry(name: 'Denmark', code: 'DK'),
  ModelCountry(name: 'Djibouti', code: 'DJ'),
  ModelCountry(name: 'Dominica', code: 'DM'),
  ModelCountry(name: 'Dominican Republic', code: 'DO'),
  ModelCountry(name: 'Ecuador', code: 'EC'),
  ModelCountry(name: 'Egypt', code: 'EG'),
  ModelCountry(name: 'El Salvador', code: 'SV'),
  ModelCountry(name: 'Equatorial Guinea', code: 'GQ'),
  ModelCountry(name: 'Eritrea', code: 'ER'),
  ModelCountry(name: 'Estonia', code: 'EE'),
  ModelCountry(name: 'Ethiopia', code: 'ET'),
  ModelCountry(name: 'Falkland Islands (Malvinas)', code: 'FK'),
  ModelCountry(name: 'Faroe Islands', code: 'FO'),
  ModelCountry(name: 'Fiji', code: 'FJ'),
  ModelCountry(name: 'Finland', code: 'FI'),
  ModelCountry(name: 'France', code: 'FR'),
  ModelCountry(name: 'French Guiana', code: 'GF'),
  ModelCountry(name: 'French Polynesia', code: 'PF'),
  ModelCountry(name: 'French Southern Territories', code: 'TF'),
  ModelCountry(name: 'Gabon', code: 'GA'),
  ModelCountry(name: 'Gambia', code: 'GM'),
  ModelCountry(name: 'Georgia', code: 'GE'),
  ModelCountry(name: 'Germany', code: 'DE'),
  ModelCountry(name: 'Ghana', code: 'GH'),
  ModelCountry(name: 'Gibraltar', code: 'GI'),
  ModelCountry(name: 'Greece', code: 'GR'),
  ModelCountry(name: 'Greenland', code: 'GL'),
  ModelCountry(name: 'Grenada', code: 'GD'),
  ModelCountry(name: 'Guadeloupe', code: 'GP'),
  ModelCountry(name: 'Guam', code: 'GU'),
  ModelCountry(name: 'Guatemala', code: 'GT'),
  ModelCountry(name: 'Guernsey', code: 'GG'),
  ModelCountry(name: 'Guinea', code: 'GN'),
  ModelCountry(name: 'Guinea-Bissau', code: 'GW'),
  ModelCountry(name: 'Guyana', code: 'GY'),
  ModelCountry(name: 'Haiti', code: 'HT'),
  ModelCountry(name: 'Heard Island and Mcdonald Islands', code: 'HM'),
  ModelCountry(name: 'Holy See (Vatican City State)', code: 'VA'),
  ModelCountry(name: 'Honduras', code: 'HN'),
  ModelCountry(name: 'Hong Kong', code: 'HK'),
  ModelCountry(name: 'Hungary', code: 'HU'),
  ModelCountry(name: 'Iceland', code: 'IS'),
  ModelCountry(name: 'India', code: 'IN'),
  ModelCountry(name: 'Indonesia', code: 'ID'),
  ModelCountry(name: 'Iran, Islamic Republic Of', code: 'IR'),
  ModelCountry(name: 'Iraq', code: 'IQ'),
  ModelCountry(name: 'Ireland', code: 'IE'),
  ModelCountry(name: 'Isle of Man', code: 'IM'),
  ModelCountry(name: 'Israel', code: 'IL'),
  ModelCountry(name: 'Italy', code: 'IT'),
  ModelCountry(name: 'Jamaica', code: 'JM'),
  ModelCountry(name: 'Japan', code: 'JP'),
  ModelCountry(name: 'Jersey', code: 'JE'),
  ModelCountry(name: 'Jordan', code: 'JO'),
  ModelCountry(name: 'Kazakhstan', code: 'KZ'),
  ModelCountry(name: 'Kenya', code: 'KE'),
  ModelCountry(name: 'Kiribati', code: 'KI'),
  ModelCountry(name: 'Korea, Democratic People\'S Republic of', code: 'KP'),
  ModelCountry(name: 'Korea, Republic of', code: 'KR'),
  ModelCountry(name: 'Kuwait', code: 'KW'),
  ModelCountry(name: 'Kyrgyzstan', code: 'KG'),
  ModelCountry(name: 'Lao People\'S Democratic Republic', code: 'LA'),
  ModelCountry(name: 'Latvia', code: 'LV'),
  ModelCountry(name: 'Lebanon', code: 'LB'),
  ModelCountry(name: 'Lesotho', code: 'LS'),
  ModelCountry(name: 'Liberia', code: 'LR'),
  ModelCountry(name: 'Libyan Arab Jamahiriya', code: 'LY'),
  ModelCountry(name: 'Liechtenstein', code: 'LI'),
  ModelCountry(name: 'Lithuania', code: 'LT'),
  ModelCountry(name: 'Luxembourg', code: 'LU'),
  ModelCountry(name: 'Macao', code: 'MO'),
  ModelCountry(name: 'Macedonia, The Former Yugoslav Republic of', code: 'MK'),
  ModelCountry(name: 'Madagascar', code: 'MG'),
  ModelCountry(name: 'Malawi', code: 'MW'),
  ModelCountry(name: 'Malaysia', code: 'MY'),
  ModelCountry(name: 'Maldives', code: 'MV'),
  ModelCountry(name: 'Mali', code: 'ML'),
  ModelCountry(name: 'Malta', code: 'MT'),
  ModelCountry(name: 'Marshall Islands', code: 'MH'),
  ModelCountry(name: 'Martinique', code: 'MQ'),
  ModelCountry(name: 'Mauritania', code: 'MR'),
  ModelCountry(name: 'Mauritius', code: 'MU'),
  ModelCountry(name: 'Mayotte', code: 'YT'),
  ModelCountry(name: 'Mexico', code: 'MX'),
  ModelCountry(name: 'Micronesia, Federated States of', code: 'FM'),
  ModelCountry(name: 'Moldova, Republic of', code: 'MD'),
  ModelCountry(name: 'Monaco', code: 'MC'),
  ModelCountry(name: 'Mongolia', code: 'MN'),
  ModelCountry(name: 'Montserrat', code: 'MS'),
  ModelCountry(name: 'Morocco', code: 'MA'),
  ModelCountry(name: 'Mozambique', code: 'MZ'),
  ModelCountry(name: 'Myanmar', code: 'MM'),
  ModelCountry(name: 'Namibia', code: 'NA'),
  ModelCountry(name: 'Nauru', code: 'NR'),
  ModelCountry(name: 'Nepal', code: 'NP'),
  ModelCountry(name: 'Netherlands', code: 'NL'),
  ModelCountry(name: 'Netherlands Antilles', code: 'AN'),
  ModelCountry(name: 'New Caledonia', code: 'NC'),
  ModelCountry(name: 'New Zealand', code: 'NZ'),
  ModelCountry(name: 'Nicaragua', code: 'NI'),
  ModelCountry(name: 'Niger', code: 'NE'),
  ModelCountry(name: 'Nigeria', code: 'NG'),
  ModelCountry(name: 'Niue', code: 'NU'),
  ModelCountry(name: 'Norfolk Island', code: 'NF'),
  ModelCountry(name: 'Northern Mariana Islands', code: 'MP'),
  ModelCountry(name: 'Norway', code: 'NO'),
  ModelCountry(name: 'Oman', code: 'OM'),
  ModelCountry(name: 'Pakistan', code: 'PK'),
  ModelCountry(name: 'Palau', code: 'PW'),
  ModelCountry(name: 'Palestinian Territory, Occupied', code: 'PS'),
  ModelCountry(name: 'Panama', code: 'PA'),
  ModelCountry(name: 'Papua New Guinea', code: 'PG'),
  ModelCountry(name: 'Paraguay', code: 'PY'),
  ModelCountry(name: 'Peru', code: 'PE'),
  ModelCountry(name: 'Philippines', code: 'PH'),
  ModelCountry(name: 'Pitcairn', code: 'PN'),
  ModelCountry(name: 'Poland', code: 'PL'),
  ModelCountry(name: 'Portugal', code: 'PT'),
  ModelCountry(name: 'Puerto Rico', code: 'PR'),
  ModelCountry(name: 'Qatar', code: 'QA'),
  ModelCountry(name: 'Reunion', code: 'RE'),
  ModelCountry(name: 'Romania', code: 'RO'),
  ModelCountry(name: 'Russian Federation', code: 'RU'),
  ModelCountry(name: 'RWANDA', code: 'RW'),
  ModelCountry(name: 'Saint Helena', code: 'SH'),
  ModelCountry(name: 'Saint Kitts and Nevis', code: 'KN'),
  ModelCountry(name: 'Saint Lucia', code: 'LC'),
  ModelCountry(name: 'Saint Pierre and Miquelon', code: 'PM'),
  ModelCountry(name: 'Saint Vincent and the Grenadines', code: 'VC'),
  ModelCountry(name: 'Samoa', code: 'WS'),
  ModelCountry(name: 'San Marino', code: 'SM'),
  ModelCountry(name: 'Sao Tome and Principe', code: 'ST'),
  ModelCountry(name: 'Saudi Arabia', code: 'SA'),
  ModelCountry(name: 'Senegal', code: 'SN'),
  ModelCountry(name: 'Serbia and Montenegro', code: 'CS'),
  ModelCountry(name: 'Seychelles', code: 'SC'),
  ModelCountry(name: 'Sierra Leone', code: 'SL'),
  ModelCountry(name: 'Singapore', code: 'SG'),
  ModelCountry(name: 'Slovakia', code: 'SK'),
  ModelCountry(name: 'Slovenia', code: 'SI'),
  ModelCountry(name: 'Solomon Islands', code: 'SB'),
  ModelCountry(name: 'Somalia', code: 'SO'),
  ModelCountry(name: 'South Africa', code: 'ZA'),
  ModelCountry(
      name: 'South Georgia and the South Sandwich Islands', code: 'GS'),
  ModelCountry(name: 'Spain', code: 'ES'),
  ModelCountry(name: 'Sri Lanka', code: 'LK'),
  ModelCountry(name: 'Sudan', code: 'SD'),
  ModelCountry(name: 'Suriname', code: 'SR'),
  ModelCountry(name: 'Svalbard and Jan Mayen', code: 'SJ'),
  ModelCountry(name: 'Swaziland', code: 'SZ'),
  ModelCountry(name: 'Sweden', code: 'SE'),
  ModelCountry(name: 'Switzerland', code: 'CH'),
  ModelCountry(name: 'Syrian Arab Republic', code: 'SY'),
  ModelCountry(name: 'Taiwan, Province of China', code: 'TW'),
  ModelCountry(name: 'Tajikistan', code: 'TJ'),
  ModelCountry(name: 'Tanzania, United Republic of', code: 'TZ'),
  ModelCountry(name: 'Thailand', code: 'TH'),
  ModelCountry(name: 'Timor-Leste', code: 'TL'),
  ModelCountry(name: 'Togo', code: 'TG'),
  ModelCountry(name: 'Tokelau', code: 'TK'),
  ModelCountry(name: 'Tonga', code: 'TO'),
  ModelCountry(name: 'Trinidad and Tobago', code: 'TT'),
  ModelCountry(name: 'Tunisia', code: 'TN'),
  ModelCountry(name: 'Turkey', code: 'TR'),
  ModelCountry(name: 'Turkmenistan', code: 'TM'),
  ModelCountry(name: 'Turks and Caicos Islands', code: 'TC'),
  ModelCountry(name: 'Tuvalu', code: 'TV'),
  ModelCountry(name: 'Uganda', code: 'UG'),
  ModelCountry(name: 'Ukraine', code: 'UA'),
  ModelCountry(name: 'United Arab Emirates', code: 'AE'),
  ModelCountry(name: 'United Kingdom', code: 'GB'),
  ModelCountry(name: 'United States', code: 'US'),
  ModelCountry(name: 'United States Minor Outlying Islands', code: 'UM'),
  ModelCountry(name: 'Uruguay', code: 'UY'),
  ModelCountry(name: 'Uzbekistan', code: 'UZ'),
  ModelCountry(name: 'Vanuatu', code: 'VU'),
  ModelCountry(name: 'Venezuela', code: 'VE'),
  ModelCountry(name: 'Viet Nam', code: 'VN'),
  ModelCountry(name: 'Virgin Islands, British', code: 'VG'),
  ModelCountry(name: 'Virgin Islands, U.S.', code: 'VI'),
  ModelCountry(name: 'Wallis and Futuna', code: 'WF'),
  ModelCountry(name: 'Western Sahara', code: 'EH'),
  ModelCountry(name: 'Yemen', code: 'YE'),
  ModelCountry(name: 'Zambia', code: 'ZM'),
  ModelCountry(name: 'Zimbabwe', code: 'ZW')
];
